name: Test GITHUB_TOKEN Permissions

on:
  workflow_dispatch:

jobs:
  test-token:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Test GitHub API Access
      run: |
        echo "Testing GitHub API access with GITHUB_TOKEN"
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}
      
    - name: Check Repository Permissions
      run: |
        echo "Checking repository permissions"
        curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/branches \
             | jq '.[] | select(.name == "gh-pages") | .name' || echo "gh-pages branch does not exist yet"